### ISSUE TITLE
Switch between "/" and "\"

### ISSUE THREAD

**Issue by FichteFoll** [liamcain/AutoFileName#10]
Windows uses backslashes "\" for file paths. While CSS or HTML only use the slash version I often want to specify the exact path on my machine (not necessarily in one of these languages). I can use this to open the path directly with another plugin for example, or to copy and paste ist somewhere.
Would be nice if you could detect whether "/" or "\" was used and base any following path separator on that.

As a side not, Python (I think; or ST2) uses file paths in a style like `/C/path/to/file.ext`. Would be nice if that triggered the autocompletition too.

**Comment by liamcain** [comment]
Just realized I can close this now. It was added a while ago.
