### ISSUE TITLE
Triggers "slow plugin" dialog every single time on starting Sublime

### ISSUE THREAD

**Issue by rchl** [liamcain/AutoFileName#11]
On every start of ST2, I get the dialog telling me that the plugin is behaving slowly.

This is on i7 2.2Ghz.

**Comment by liamcain** [comment]
I'll take a look at it.  Thanks.

**Comment by liamcain** [comment]
I made some changes that should speed things up.  Let me know if this problem is fixed.

**Comment by rchl** [comment]
I've later realized that I had second Sublime's window with a lot of files open and that was triggering slow plugin dialog.
But not saying this is not a problem. I often have many files open and this is the only plugin that triggers this dialog.

Anyways, I haven't yet tried your changes with many files. Will try that later. I use this plugin with C++ code and I need to apply my local changes before it's usable. Have to adapt them to your latest version. Eventually I should clean them up and make into a pull request.

Anyways, looking at your changes, I've noticed that you've added on_modified handler. This one, together with on_selection_modified is one of those callbacks that are called a lot on restoring session and probably it doesn't help with original problem.

**Comment by rchl** [comment]
Like I suspected, new version is actually slower. It's easier to trigger "slow plugin" dialog. I don't even have to have many files open.
