### ISSUE TITLE
Settings not read from user preferences

### ISSUE THREAD

**Issue by rchl** [liamcain/AutoFileName#12]
Main.sublime-menu defines two pref files - one for default settings and one for user settings. The problem is that the plugin always seems to read from default settings.

I would obviously prefer to store my overrides in the user settings so that they are not overridden on update.

**Comment by rchl** [comment]
The problem is that user settings entry points to "${packages}/User/Preferences.sublime-settings" while it should point to "${packages}/User/autofilename.sublime-settings"

**Comment by liamcain** [comment]
Thanks for this.  Fixed for the next commit.

**Comment by liamcain** [comment]
Fixed.

**Comment by rchl** [comment]
I think you have not pushed this.
