### ISSUE TITLE
Adds extra html opening tag (<) to autocomplete

### ISSUE THREAD

**Issue by billaddison** [liamcain/AutoFileName#13]
After enabling the AutoFileName plugin, when using auto-complete for HTML tags it now adds an extra opening tag: <<div> etc.

**Comment by liamcain** [comment]
This is a bug in the old version of zencoding.  New version here: https://github.com/sergeche/zencoding-sublime

**Comment by billaddison** [comment]
Thanks Liam, I read that online but I didn't (don't) have zencoding installed.

**Comment by liamcain** [comment]
Hmm.  Well I assure you the bug is unrelated to AutoFileName.  Maybe it's the Tag package?
