### ISSUE TITLE
Unwanted delete behavior when pressing backspace

### ISSUE THREAD

**Issue by rchl** [liamcain/AutoFileName#19]
In a text file, f.e.

```
A path: C:\Windows\Foo\Bar
```

go at the end of the line and press backspace. When cursor reaches backslash it selects whole text in a file and next backspace deletes it. I understand that it might be somewhat wanted when autocompleting paths but it's too intrusive as it is.

Hmm, I'm not sure exactly about the repro steps but it triggers when not wanted.

**Comment by liamcain** [comment]
As I mentioned on the forum, I haven't tested this build on Windows, so it doesn't work very well with using \ slashes.  This backspace behavior triggers when deleting a / slash.  It deletes the / and selects the previous directory, making it easier to backspace through long paths.  I'm personally quite fond of the behavior and instead of getting rid of it, would rather see it fixed for windows.  Feel free to send a pull request.

**Comment by rchl** [comment]
It's not really Windows specific. Another example (c++ code):

#ifdef FOO
    void MyCoolMethod();
#endif // FOO

Now backspacing from the end, after deleting second slash (from the right), whole block is selected and removed when pressing backspace again.

**Comment by liamcain** [comment]
Oh.  Whoops!  That was my bad.  Pushing a fix now.  I forgot to check if the cursor as at the end of a path :/  Sorry.

**Comment by rchl** [comment]
Thanks. I guess that was my initial problem (I wasn't sure about repro steps).

**Comment by liamcain** [comment]
Yeah. No problem.  I was just confused since you mentioned it occurs when completing windows paths. Threw me off...

**Comment by rchl** [comment]
BTW. I think this feature should have a switch. It just gets in a way in least expected moments. For example when backspacing in :

<a href="http://foo"

The feature doesn't seem to do much more than alt+backspace (delete word) so IMO it would be better if user would decide on his own if he wants to delete by word or just single characters.

**Comment by liamcain** [comment]
Feel free to send a pull request with a setting to toggle it.  While the feature is similar to alt+backspace most of the time, it does have an advantage when the path has spaces or special characters.  That was my primary motivation for adding it.
