### ISSUE TITLE
Wrong basepath on Win8

### ISSUE THREAD

**Issue by barabasz** [liamcain/AutoFileName#21]
It doesn't refer to the folder of open file but to the root of system drive ("c:\").

I have empty afn_proj_root, and enabled afn_use_project_root.

Sometimes instead of root folder it refers to
"C:\ProgramData\Microsoft\Windows\Start Menu\Programs"
- Sublime Text 2 shortcut location.

**Comment by liamcain** [comment]
Fixed this on the st3 branch.
