### ISSUE TITLE
Sublime Text 3 Support

### ISSUE THREAD

**Issue by charlesmudy** [liamcain/AutoFileName#24]
I like your plugin and I use it regularly, when do you plan on supporting Sublime Text 3 ?

**Comment by liamcain** [comment]
I'll get to this soon.

**Comment by webuniverseio** [comment]
charlesmudy - if you like you can use this patch for now: https://github.com/BoundInCode/AutoFileName/pull/25
Upd: ops, image size don't work, missed something. Path auto-complemetion works though.

**Comment by charlesmudy** [comment]
The size I don't even need, just the path and it's perfectly working ... thanks for the support.

**Comment by igor10k** [comment]
@BoundInCode any progress on ST3 support?

**Comment by hkutcher** [comment]
+1 for ST3 support.

**Comment by liamcain** [comment]
This package already supports ST3.
