### ISSUE TITLE
ctrl+space is already binded in MACOS

### ISSUE THREAD

**Issue by DimitryDushkin** [liamcain/AutoFileName#27]
ctrl+space is already binded in MACOS to global search. Please change to something else like alt(option)+space.

**Comment by liamcain** [comment]
AutoFileName doesn't bind anything to control+space. Control+space is Sublime Text's default shortcut for autocomplete. So if you want to change the shortcut to manually trigger autocomplete you'll have to do that in your User Keybindings file.
