### ISSUE TITLE
Miss AutoFileName in Package Control for ST3

### ISSUE THREAD

**Issue by pustovalov** [liamcain/AutoFileName#36]
AutoFileName is missing in Package Control for ST3.

Installed plugins:
![2](https://f.cloud.github.com/assets/1568885/950437/3b1864ee-038f-11e3-83f9-926df9a38da3.jpg)

Package Control:
![1](https://f.cloud.github.com/assets/1568885/950444/570f3600-038f-11e3-96b7-bd6f43889ba9.jpg)

Yes, I know that you can download a branch ST3, archive it, rename in AutoFileName.sublime-package. But it's terribly inconvenient.

**Comment by liamcain** [comment]
I haven't gotten a chance to change AutoFileName for the new version of Package Control. Hopefully I'll have some free time soon.

**Comment by liamcain** [comment]
AutoFileName is in Package Control now.
