### ISSUE TITLE
Sometimes, I don't want the image height and width added in an image tag

### ISSUE THREAD

**Issue by KatieK2** [liamcain/AutoFileName#43]
I love this plug-in - thank you for working on it.  

Sometimes, I don't want the image height and width attributes added to an image tag.  For example, when I'm working on a responsive build and I want the image dimensions to be handled by CSS. I agree that doing so should be the default setting, but I wish that there was a preference I could set to enable or disable this behavior.

**Comment by liamcain** [comment]
There is already a setting to disable this behavior. Try setting `"afn_insert_dimensions": false` in your user preferences.

**Comment by KatieK2** [comment]
Awesome - thank you!
