### ISSUE TITLE
option to not append "/" for directories

### ISSUE THREAD

**Issue by pjv** [liamcain/AutoFileName#6]
when using this plugin to dig into subdirs to find an image file, i find that i am putting the cursor inside the " ", then hitting the "/" key to trigger auto-completion, then when i choose a directory from the completion list, in order to trigger completions for the contents of that directory, i either have to hit ctrl-space or backspace over the "/" and then re-type "/". both of those things slow me down.

it would be really cool if there was a way to see the trailing "/" on the directory name in the completion list, but have an option to insert the directory name WITHOUT the trailing "/" when you do the completion so that you can just keeping typing "/" after each insertion to keep triggering the next auto-complete list.

i have never found any documentation for the auto completions api, but i did read [here](http://www.sublimetext.com/forum/viewtopic.php?f=6&t=2846&p=13327&hilit=completion#p13351) that there is a way to put one thing into the completion list but insert something else when the completion is done.

**Comment by liamcain** [comment]
Great suggestion.  I just added this.  I'll push the update soon.
