### ISSUE TITLE
How add first slash? - SOLVED at 2017 + ST3!

### ISSUE THREAD

**Issue by Kcko** [liamcain/AutoFileName#69]
I set 
    "afn_use_project_root": true,
    "afn_proj_root": "",

When i choosing some file in some directory (selection now work correctly).
But final path is without opening slash , see http://files.rjwebdesign.cz/i/20140910-115755---595x346---t---pn.png

How can I do this? (Im using rewrite mod and and need to set full path with opening slash)

BAD   assets/gfx/picture.jpg
GOOD /assets/gfx/picture.jpg

Thx for idea.

**Comment by evoactivity** [comment]
Been an issue for a while, have a look at this comment from another issue. https://github.com/BoundInCode/AutoFileName/issues/34#issuecomment-34754251

Setting up your project file as shown there will work. Will need to be done per project.

**Comment by stubear** [comment]
The "fix" works but it's a real pain in the ass. I'm going to use FuzzyFilePath for the time being until this issue is resolved in a global manner so I don't need to edit each project I'm working on.

**Comment by Kcko** [comment]
Yes its a true.

but it was rather complicated to find a solution.

My Solution: Im using Win 10, with disk C and Z (with my webs).
My Settiings: 

"afn_use_project_root": true,
"afn_proj_root": "z:www/project123/",  (you see right, without "/", only z: or c: )

and now when i type "/" i finally get folders in this project :-) 

BAZINGA!
