### ISSUE TITLE
constructing path bug in beta branch

### ISSUE THREAD

**Issue by pjv** [liamcain/AutoFileName#7]
cool on all the new changes! that was quick.

i just started playing with the new beta and found one issue:

great how the completions list shows the trailing slash for directories but then doesn't include it when you do the completion now. however, when i type the next slash (e.g. "/img/") the completions i get are once again at the root of the project directory instead of being the completions for what's inside the "img" directory.

**Comment by liamcain** [comment]
Thanks for catching that.  Good thing I put this in a beta branch. :)  I just pushed a fix.  It should work a lot better now.

**Comment by pjv** [comment]
yes, this is working perfectly now. thanks!
