### ISSUE TITLE
not working for me in .less files

### ISSUE THREAD

**Issue by pjv** [liamcain/AutoFileName#8]
not sure whether this is a scope problem or an issue with the less package or something in AutoFileName, but i am not seeing completions in .less files. when i look in the console and try to get the scope where i think completions should be happening, it seems a little confusing.

anyway, in a .less file, using the LESS package for ST2 from [here](https://github.com/danro/LESS-sublime), i get no completions inside the following ( | = cursor):

```
body {
  background-image: url("|");
}
```

if i change the syntax to css then i get completions in the same selector/position.

one of the confusing things is that looking at the scope selector in the console with the syntax set to LESS, that selector is not seen as a string even though it is inside double-quotes. that's why i am wondering if it might not be a problem with the less package.

EDIT: i raised an [issue](https://github.com/danro/LESS-sublime/issues/8) in the less package repo.

**Comment by liamcain** [comment]
I believe this is actually an issue with Zencoding interfering.  When I disabled the zencoding package, AutoFileName worked just fine.  Try adding "Zencoding" to your list of disabled packages and let me know if the problem persists.

**Comment by pjv** [comment]
thanks, yes, you are right that disabling zencoding allows AutoFileName completions to work for me.

i still think that the sublime-less package should be seeing that parameter as a string though...
